import streamlit as st
import pandas as pd
from database.models import (
    get_student_by_id, get_student_by_user_id,
    get_study_plans_for_student, update_study_plan_status, get_all_subjects
)
from planner.study_planner import generate_personalized_study_plan, record_task_improvement_and_adapt
from analytics.subject_risk import calculate_subject_level_risks
from analytics.topic_analysis import identify_topic_weaknesses
from utils.styling import render_status_pill
from utils.helpers import render_alert_box

def render_study_planner_view():
    """Render Personalized & Adaptive Study Planner Page."""
    user = st.session_state.get("user") or {}
    profile = st.session_state.get("profile") or {}
    if not profile:
        profile = get_student_by_user_id(user.get("id", 1)) or {}

    student_id = profile.get("id", 1)
    if "override_student_id" in st.session_state:
        student_id = st.session_state["override_student_id"]
        profile = get_student_by_id(student_id) or profile

    name = profile.get("full_name", "Student")
    risk_level = profile.get("current_risk_level", "LOW")

    st.markdown('<div class="header-title">Personalized Adaptive Study Planner</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="header-subtitle">Intelligent study prioritization for {name} based on risk, topic weaknesses, and historical exam importance</div>', unsafe_allow_html=True)

    # 1. Action Banner
    render_alert_box(
        "🧠 <b>ADAPTIVE ENGINE ACTIVE:</b> Tasks are dynamically generated by combining your dropout risk, subject marks, "
        "topic quiz scores, and historical examination importance scores. Marking tasks complete or recording quiz improvements "
        "will automatically adapt future study priorities.",
        severity="info"
    )

    # Fetch current study plans or generate if empty
    plans = get_study_plans_for_student(student_id)
    if not plans:
        plans = generate_personalized_study_plan(student_id)

    col1, col2 = st.columns([0.65, 0.35])

    with col1:
        st.markdown("### 📅 Today & Upcoming Study Schedule")

        for p in plans:
            p_id = p["id"]
            prio = p["priority"]
            dur = p["duration_minutes"]
            subj_name = p["subject_name"]
            t_name = p["topic_name"]
            status = p["status"]
            reason = p["reason"]

            card_border = "#EF4444" if prio == "HIGH" else ("#F59E0B" if prio == "MEDIUM" else "#10B981")
            status_bg = "#E2E8F0" if status == "Not Started" else ("#FEF3C7" if status == "In Progress" else "#D1FAE5")

            st.markdown(f"""
            <div style="background: white; border-left: 5px solid {card_border}; padding: 16px; border-radius: 10px; border-top: 1px solid #E2E8F0; border-right: 1px solid #E2E8F0; border-bottom: 1px solid #E2E8F0; margin-bottom: 14px;">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <span style="font-weight: 700; font-size: 1.05rem; color: #0F172A;">{subj_name} — {t_name}</span>
                    <span style="background: {status_bg}; padding: 4px 10px; border-radius: 6px; font-weight: 600; font-size: 0.8rem; color: #1E293B;">Status: {status}</span>
                </div>
                <div style="font-size: 0.88rem; color: #475569; margin-top: 6px;">⏱️ Duration: <b>{dur} mins</b> | Priority: <b>{prio}</b></div>
                <div style="font-size: 0.85rem; color: #64748B; margin-top: 4px; font-style: italic;">Reason: {reason}</div>
            </div>
            """, unsafe_allow_html=True)

            # Interactive Status Toggle
            c_stat, c_regen = st.columns([0.7, 0.3])
            with c_stat:
                new_stat = st.selectbox(
                    f"Update Task Status ({subj_name}: {t_name})",
                    ["Not Started", "In Progress", "Completed"],
                    index=["Not Started", "In Progress", "Completed"].index(status),
                    key=f"status_sel_{p_id}"
                )
                if new_stat != status:
                    update_study_plan_status(p_id, new_stat)
                    st.toast(f"Task status updated to '{new_stat}'")
                    st.rerun()

    with col2:
        st.markdown("### 🔄 Simulate Score Improvement")
        st.caption("Demonstrate closed-loop adaptive planning by recording an improved quiz score for a weak topic:")

        # Form to record improved score
        subject_risks = calculate_subject_level_risks(student_id)
        if subject_risks:
            subj_options = {s["subject_name"]: s["subject_id"] for s in subject_risks}
            sel_s_name = st.selectbox("Select Subject", list(subj_options.keys()), key="sim_subj_sel")
            sel_s_id = subj_options[sel_s_name]

            weaknesses = identify_topic_weaknesses(student_id, sel_s_id)
            if weaknesses:
                top_options = {w["topic_name"]: w["topic_id"] for w in weaknesses}
                sel_t_name = st.selectbox("Select Weak Topic", list(top_options.keys()), key="sim_top_sel")
                sel_t_id = top_options[sel_t_name]

                st.write(f"**Selected:** {sel_s_name} ➔ {sel_t_name}")
                new_score = st.slider("New Assessment Score (%)", min_value=50, max_value=95, value=85, step=5)

                if st.button("🚀 Record Score & Adapt Study Plan", use_container_width=True):
                    res = record_task_improvement_and_adapt(student_id, sel_s_id, sel_t_id, new_score)
                    st.success(res["message"])
                    st.rerun()

        st.markdown("---")
        if st.button("⚡ Regenerate Fresh Plan", use_container_width=True):
            generate_personalized_study_plan(student_id)
            st.success("Study plan regenerated.")
            st.rerun()
